### PR TITLE
OPT-361 Fix lack of entry point

### PR DESCRIPTION
**Pull request by alanclarke**

### CODE REVIEW

**Comment by KwanMan** [comment]
This was intentional btw to force the user to be explicit in either doing

```
import QubitReact from 'qubit-react/wrapper'
// or
const experience = require('qubit-react/experience')
```
since neither of them is more "main" than the other, just equal but different sides of the puzzle

Now that we have actually integrated the `/experience` part directly into Experiences and the user will not have to call it directly anymore, I would actually advocate the `/wrapper` version to be the main export since that's the part our clients will be using mainly

**Comment by alanclarke** [comment]
@KwanMan unfortunately this breaks yuge and means people can't assess the size of the package. I wanted to make the entry make both accessible, after discussing with @oliverwoodings we decided on the experiences point being the default

**Comment by alanclarke** [comment]
If we make wrapper the default yuge will give a misleading number for the size of this package

**Comment by oliverwoodings** [comment]
This is what i think an 'ideal' could be:

1. Release a minor version bump that sets the default entry point to `/experiences`
1. Release a major version bump for qubit-react which contains _only_ the wrapper. Release a separate, internal package that contains the experience code (since no clients should be using that directly now).

**Comment by KwanMan** [comment]
fairy dos

**Pull request merged**
